//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshopDL.b2b {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.msan.hr/B2B/", ConfigurationName="b2b.B2BProductServiceSoap")]
    public interface B2BProductServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsList(string ProductCode, string ProductType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsGalleryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsGalleryList(string ProductCode, string ProductType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsPriceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsPriceList(string ProductCode, string ProductType, string Brand, bool OnPromotion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsPriceListBySalesChannel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsPriceListBySalesChannel(string ProductCode, string ProductType, string Brand, bool OnPromotion, int salesChannelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsAvailability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsAvailability(string ProductCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsSpecification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsSpecification(string ProductCode, string ProductType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsSpecificationIceCat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsSpecificationIceCat(string ProductCode, string ProductType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsReplacementList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsReplacementList(string ProductCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsRelatedList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsRelatedList(string ProductCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsBarcodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsBarcodes(string ProductCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetCategoriesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetCategoriesList(int CategoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.msan.hr/B2B/GetProductsCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetProductsCategory(int CategoryTypeID, string ProductCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface B2BProductServiceSoapChannel : eshopDL.b2b.B2BProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B2BProductServiceSoapClient : System.ServiceModel.ClientBase<eshopDL.b2b.B2BProductServiceSoap>, eshopDL.b2b.B2BProductServiceSoap {
        
        public B2BProductServiceSoapClient() {
        }
        
        public B2BProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B2BProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetProductsList(string ProductCode, string ProductType) {
            return base.Channel.GetProductsList(ProductCode, ProductType);
        }
        
        public System.Data.DataSet GetProductsGalleryList(string ProductCode, string ProductType) {
            return base.Channel.GetProductsGalleryList(ProductCode, ProductType);
        }
        
        public System.Data.DataSet GetProductsPriceList(string ProductCode, string ProductType, string Brand, bool OnPromotion) {
            return base.Channel.GetProductsPriceList(ProductCode, ProductType, Brand, OnPromotion);
        }
        
        public System.Data.DataSet GetProductsPriceListBySalesChannel(string ProductCode, string ProductType, string Brand, bool OnPromotion, int salesChannelID) {
            return base.Channel.GetProductsPriceListBySalesChannel(ProductCode, ProductType, Brand, OnPromotion, salesChannelID);
        }
        
        public System.Data.DataSet GetProductsAvailability(string ProductCode) {
            return base.Channel.GetProductsAvailability(ProductCode);
        }
        
        public System.Data.DataSet GetProductsSpecification(string ProductCode, string ProductType) {
            return base.Channel.GetProductsSpecification(ProductCode, ProductType);
        }
        
        public System.Data.DataSet GetProductsSpecificationIceCat(string ProductCode, string ProductType) {
            return base.Channel.GetProductsSpecificationIceCat(ProductCode, ProductType);
        }
        
        public System.Data.DataSet GetProductsReplacementList(string ProductCode) {
            return base.Channel.GetProductsReplacementList(ProductCode);
        }
        
        public System.Data.DataSet GetProductsRelatedList(string ProductCode) {
            return base.Channel.GetProductsRelatedList(ProductCode);
        }
        
        public System.Data.DataSet GetProductsBarcodes(string ProductCode) {
            return base.Channel.GetProductsBarcodes(ProductCode);
        }
        
        public System.Data.DataSet GetCategoriesList(int CategoryTypeID) {
            return base.Channel.GetCategoriesList(CategoryTypeID);
        }
        
        public System.Data.DataSet GetProductsCategory(int CategoryTypeID, string ProductCode) {
            return base.Channel.GetProductsCategory(CategoryTypeID, ProductCode);
        }
    }
}
